### ISSUE TITLE
`hello_triangle.nim` does't compile due to incorrect Use / UseProgram procedure name

### ISSUE THREAD

**Issue by Samulus** [jackmott/easygl#2]
I tried to compile the ``hello_triangle.nim`` example but I couldn't compile it due to [this line](https://github.com/jackmott/easygl/blob/master/examples/getting_started/hello_triangle.nim#L79).

The `UseProgram` wrapper procedure is actually just called `Use` ([see here](https://github.com/jackmott/easygl/blob/master/src/easygl.nim#L320))

I would rename `Use` to be `UseProgram` but you could also change the procedure in ``hello_triangle.nim`` to be ``Use``. I didn't a pull request because I'm not sure which you would prefer.

**Comment by jackmott** [comment]
Thanks, I probably changed the easygl wrapper and forget to go update hello_triangle, I'll fix it up tonight.

**Comment by jackmott** [comment]
fixed

**Comment by dom96** [comment]
@jackmott Not sure if I mentioned this to you already, but it would be great if you followed the Nim code conventions. i.e. don't name your templates/procs with a capital letter at the start.

**Comment by jackmott** [comment]
Ok I can fix that, but just noticed that nimble can no longer build because glm now requires nim 17.3 which I do not have, and I can't figure out how to request an older version.

requires "glm 0.2.0" doesn't seem to work.

**Comment by dom96** [comment]
You can try ``requires "glm#<commit_hash>"`` where ``commit_hash`` is the git commit hash of the version you want.

**Comment by jackmott** [comment]
that did it!
now to see if vs code's nim plugin has rename symbol

**Comment by jackmott** [comment]
@dom96 what is the best way to be able to compile all of the src files in the examples subdir at once? is there a way to set that up in the nimble file?

**Comment by dom96** [comment]
not currently. I mean you can write a task that does it, but Nimble doesn't have any default functionality for that.

**Comment by jackmott** [comment]
allright, lowerecased it.
